### ISSUE TITLE
Use of os.cpu_count() breaks parmapper in older ( 3.4 and below) Python versions

### ISSUE THREAD

**Issue by cmarquardt** [Jwink3101/parmapper#1]
Hello,

thank you for parmapper!

In one of your recent commits, you switched from using `mp.cpu_count()` to `os.cpu_count()`. As far as I could find out, the function was only added to the `os` module in Python 3.4; thus older versions of Python fail to compile. On the other hand, `mp` continues to support `cpu_count()`, I believe.

Would it be a problem to revert back to using the `mp` version?

**Comment by Jwink3101** [comment]
Yes, 100% fine with me. I'll do it tomorrow when I am back on my computer or I'll accept a merge request. 

Thanks for bringing it to my attention. I am happy to support older python versions as long as it is easy to do. But I don't use anything older than 3.7 anymore so I missed it.

**Comment by cmarquardt** [comment]
Ui - that was fast. Thank you!
